name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        run: |
          curl ${{secrets.TEST_URL}} > hidden.txt
          echo "Retrieved hidden information"
          echo "-----"
