name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        run: |
          curl ${{secrets.TESTURL}}
          echo "-----"
          echo -n "${{ secrets.TESTURL }}" >> foo && cut -c1-3 foo && cut -c4- foo
