name: Run Tests

on:
  [push, pull_request]
  
jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Action test
        run: |
          touch "${{secrets.SOMETHING}}"
          ls | echo
